version: '3.8'

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  nectia:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  mongo-data:
  redis_data: